version: "3.8"

services:
  qlda-be:
    image: registry.gitlab.com/tuanxx31/qlda/qlda-be:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3100

      - DATABASE_HOST=db-mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=qlda
      - DATABASE_TYPE=mysql

      - JWT_SECRET=${JWT_SECRET}
      - TZ=Asia/Ho_Chi_Minh

      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=https://qlda-api.sclould.com/auth/google/callback
      - FRONTEND_URL=https://qlda.sclould.com

    expose:
      - "3100"
    volumes:
      # Mount volume external để lưu trữ file uploads
      - qlda-uploads:/qlda/be/uploads
    networks:
      shared-network:
        aliases:
          - qlda-be



  qlda-fe:
    image: registry.gitlab.com/tuanxx31/qlda/qlda-fe:latest
    restart: unless-stopped
    environment:
      - PORT=8081
      - API_BASE=https://qlda-api.sclould.com
      - TZ=Asia/Ho_Chi_Minh
    expose:
      - "8081"
    networks:
      shared-network:
        aliases:
          - qlda-fe

volumes:
  # Volume external để lưu trữ file uploads (avatar, comment attachments)
  qlda-uploads:
    external: true

networks:
  shared-network:
    external: true
